import { INewPlan } from "@/services/plan";

export const PLANS: INewPlan[] = [
  {
    id: "cm1pc3hxl000cuyxjshqjopuk",
    productId: 350713,
    productName: "Starter",
    variantId: 529169,
    name: "Monthly",
    description: "<p>For simple websites with less than 30 unique pages</p>",
    price: "900",
    isUsageBased: false,
    interval: "month",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 2,
    packageSize: 300,
    isPopular: false,
  },
  {
    id: "cm1pc3iqr000duyxjf8ghocrc",
    productId: 350713,
    productName: "Starter",
    variantId: 529173,
    name: "Annually",
    description: "<p>For simple websites with less than 30 unique pages</p>",
    price: "9000",
    isUsageBased: false,
    interval: "year",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 3,
    packageSize: 300,
    isPopular: false,
  },
  {
    id: "cm1pc3eve0008uyxjtisu0l5j",
    productId: 350711,
    productName: "Growth",
    variantId: 518459,
    name: "Monthly",
    description: "<p>Suitable for websites with 300 to 1,000 unique pages</p>",
    price: "2900",
    isUsageBased: false,
    interval: "month",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 2,
    packageSize: 3000,
    isPopular: false,
  },
  {
    id: "cm1pc3fmb0009uyxj8vinphcx",
    productId: 350711,
    productName: "Growth",
    variantId: 529200,
    name: "Annually",
    description: "<p>Suitable for websites with 300 to 1,000 unique pages</p>",
    price: "29000",
    isUsageBased: false,
    interval: "year",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 3,
    packageSize: 3000,
    isPopular: false,
  },
  {
    id: "cm1pc3gdx000auyxj45k5b6y1",
    productId: 350715,
    productName: "Pro",
    variantId: 518463,
    name: "Monthly",
    description:
      "<p>Suitable for large websites with 5,000 unique pages or above</p>",
    price: "9900",
    isUsageBased: false,
    interval: "month",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 0,
    packageSize: 30000,
    isPopular: true,
  },
  {
    id: "cm1pc3h54000buyxj1sb5udhk",
    productId: 350715,
    productName: "Pro",
    variantId: 529199,
    name: "Annually",
    description:
      "<p>Suitable for large websites with 5,000 unique pages or above</p>",
    price: "99000",
    isUsageBased: false,
    interval: "year",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 1,
    packageSize: 30000,
    isPopular: true,
  },
  {
    id: "cm1pc3hxl000cuyxjshqjoppo",
    productId: 350715,
    productName: "Enterprise",
    variantId: 518463,
    name: "Monthly",
    description:
      "<p>Dedicated support and infrastructure for your company.</p>",
    price: "contact us",
    isUsageBased: false,
    interval: "month",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 0,
    packageSize: Infinity,
    isPopular: false,
  },
  {
    id: "cm1pc3iqr000duyxjf8ghocpop",
    productId: 350715,
    productName: "Enterprise",
    variantId: 529199,
    name: "Annually",
    description:
      "<p>Dedicated support and infrastructure for your company.</p>",
    price: "contact us",
    isUsageBased: false,
    interval: "year",
    intervalCount: 1,
    trialInterval: null,
    trialIntervalCount: null,
    sort: 1,
    packageSize: Infinity,
    isPopular: false,
  },
];
